[project]
name = "dash"
version = "0.1.0"
description = "Two dimensional game engine and editor"
dependencies = [
  "pygame-ce>=2.5.2",
]
requires-python = "==3.13.*"
readme = "README.md"
license = {text = "GPL-3.0-or-later"}
